# v-nord 1.8
legacy_layout=false
blacklist=pamac-manager,lact,ghb,bitwig-studio,ptyxis,yumex,EDLaunch.exe

# DISPLAY CONTROL (Starts HUD hidden. Use Right-Shift + F12 to toggle)
# no_display

# PERFORMANCE & METRICS
fps
frame_timing

# HARDWARE MONITORS
gpu_stats
vram
gpu_temp
cpu_stats
cpu_temp
ram
io_read
io_write
# show_fps_limit
wine

# POSITION & LAYOUT
horizontal
horizontal_stretch=0
hud_no_margin
round_corners=10
background_alpha=0.6
position=top-center

# BINDINGS
toggle_hud=Shift_R+F12
toggle_hud_position=Shift_R+F11
toggle_fps_limit=Shift_L+F1
toggle_logging=Shift_L+F2

# NORD COLORS
# Polar Night (backgrounds/dark): #2e3440, #3b4252, #434c5e, #4c566a
# Snow Storm (text/light): #d8dee9, #e5e9f0, #eceff4
# Frost (ice blues): #8fbcbb, #88c0d0, #81a1c1, #5e81ac
# Aurora (accents): #bf616a (red), #d08770 (orange), #ebcb8b (yellow), #a3be8c (green), #b48ead (purple)

gpu_color=88c0d0
cpu_color=bf616a
background_color=2e3440
text_color=eceff4
horizontal_separator_color=4c566a

# Dynamic Thresholds
fps_value=30,60
fps_color=bf616a,ebcb8b,a3be8c

gpu_load_value=60,90
gpu_load_color=a3be8c,ebcb8b,bf616a

cpu_load_value=60,90
cpu_load_color=a3be8c,ebcb8b,bf616a

# Static Component Colors
frametime_color=d08770
vram_color=b48ead
ram_color=81a1c1
io_color=d08770
wine_color=bf616a
engine_color=d08770
media_player_color=e5e9f0
network_color=d08770
battery_color=8fbcbb
