# Basic setup with popular plugins

# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="bira"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Aliases
source $HOME/git/toolbox/aliases/my_aliases.sh
source $HOME/git/toolbox/aliases/git_aliases.sh

# Exports
export EDITOR='fresh'
export VISUAL='fresh'
export PATH="$HOME/.local/bin:$PATH"

# Basic git prompt
# autoload -Uz vcs_info
# precmd_vcs_info() { vcs_info }
# precmd_functions+=( precmd_vcs_info )
# setopt prompt_subst
# zstyle ':vcs_info:git:*' formats '%F{yellow}(%b)%f'
# PROMPT='%F{cyan}%~%f ${vcs_info_msg_0_}%F{green}❯%f '
# RPROMPT='%F{white}%*%f'  # Right prompt with time

# Modern dark
# PROMPT='%F{#50FA7B}%~%f %F{#FF79C6}❯%f '

# Solarized
# PROMPT='%F{136}%n%f@%F{166}%m%f %F{33}%~%f %# '

# Fastfetch
fastfetch
