#!/usr/bin/env bash
# font: "JetBrainsMono Nerd Font 11"

#!/usr/bin/env bash

# Uses clean Nerd Font glyphs: Network (󰖩), Audio (󰕾), Bluetooth (󰂯)
options="󰖩 Network (nmtui)\n󰕾 Audio Mixer (wiremix)\n󰂯 Bluetooth (bluetui)"

choice=$(echo -e "$options" | rofi -dmenu -p "System Config" -theme-str 'window { width: 320px; height: 180px; font: "JetBrainsMono Nerd Font 11"; }')

case "$choice" in
    *"Network"*)
        kitty --class floating_tui -e nmtui
        ;;
    *"Audio"*)
        kitty --class floating_tui -e wiremix
        ;;
    *"Bluetooth"*)
        kitty --class floating_tui -e bluetui
        ;;
esac
